name: Build WASM

concurrency:
  group: "wasm-build-${{ github.sha }}"
  cancel-in-progress: false

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Name of the uploaded WASM artifact"
        value: wasm-build

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup toolchain install stable --profile minimal

      - name: Rust Cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Upload WASM artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: wasm-build
          path: target/wasm32-unknown-unknown/release/*.wasm
          retention-days: 1
